Update ado_git.yml

diff --git a/.github/workflows/ado_git.yml b/.github/workflows/ado_git.yml
--- a/.github/workflows/ado_git.yml
+++ b/.github/workflows/ado_git.yml
@@ -39,26 +39,26 @@ jobs:
         gh extension install github/gh-ado2gh
         gh ado2gh --help
 
-    - name: Install Azure CLI
-      run: |
-        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+    # - name: Install Azure CLI
+    #   run: |
+    #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
     
-    - name: Install Azure DevOps extension for Azure CLI
-      run: |
-        az extension add --name azure-devops || echo "Extension already installed"
+    # - name: Install Azure DevOps extension for Azure CLI
+    #   run: |
+    #     az extension add --name azure-devops || echo "Extension already installed"
     
-    - name: Validate Azure DevOps PAT
-      continue-on-error: true
-      env:
-        AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
-      run: |
-        az devops configure --defaults organization=https://dev.azure.com/${{ env.ADO_ORG }}
-        if az devops project list --output none; then
-          echo "Azure DevOps PAT is valid."
-        else
-          echo "Invalid Azure DevOps PAT or insufficient permissions."
-          exit 1
-        fi
+    # - name: Validate Azure DevOps PAT
+    #   continue-on-error: true
+    #   env:
+    #     AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
+    #   run: |
+    #     az devops configure --defaults organization=https://dev.azure.com/${{ env.ADO_ORG }}
+    #     if az devops project list --output none; then
+    #       echo "Azure DevOps PAT is valid."
+    #     else
+    #       echo "Invalid Azure DevOps PAT or insufficient permissions."
+    #       exit 1
+    #     fi
 
     - name: Migrate repository from ADO to GitHub
       run: |
